### ISSUE TITLE
微信没有群组

### ISSUE THREAD

**Issue by crazecoder** [Jamling/SmartIM4IntelliJ#37]
微信不支持群组吗？还是我操作姿势不对？

**Comment by Jamling** [comment]
微信登录成功后，在freinds选项卡，第一个分组group就是群组了。

**Comment by oqyj** [comment]
java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1458)
	at java.util.Collections.sort(Collections.java:141)
	at cn.ieclipse.wechat.WXContactTreeNode.update(WXContactTreeNode.java:36)
	at cn.ieclipse.wechat.WXContactView.doUpdateContacts(WXContactView.java:118)
	at cn.ieclipse.smartim.views.IMContactView$4.run(IMContactView.java:89)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by oqyj** [comment]
微信 群组没有数据，点不开，会报这个错

**Comment by oqyj** [comment]
@Jamling
